### ISSUE TITLE
Using congress_forms gem without CWC

### ISSUE THREAD

**Issue by orlando** [EFForg/congress_forms#2]
Hello

We contacted requesting access to the CWC following instructions here https://www.house.gov/doing-business-with-the-house/communicating-with-congress-cwc and we were denied to join. We wanted to integrate with our Community (https://community.debtcollective.org) to make it easier for debtors contact their house representatives.

Do you know any alternatives that can help us do the integration? The previous version (https://github.com/EFForg/phantom-of-the-capitol) this registration wasn't needed but I see it doesn't support reCAPTCHA and is not being actively maintained.

Any help is really appreciated.

Thanks!

**Comment by wioux** [comment]
Hi @orlando. Unfortunately our tools all use CWC to message house reps, due to thorough adoption of reCAPTCHA on their contact forms. There are remnants of house.gov webform support in some projects, but none of that is working or maintained.

Not sure this would fit your needs but there are some good open source resources for contacting congress by other means:

  - [unitedstates/congress-legislators](https://github.com/unitedstates/congress-legislators/blob/master/legislators-current.yaml) maintains phone numbers and social media handles
  - [OpenSourceActivismTech/call-power](https://github.com/OpenSourceActivismTech/call-power) for guided phone campaigns

Alternatively, votervoice.net and popvox.com both offer message delivery as a service. I haven't used them though and can't personally vouch for reliability.

Best of luck.

**Comment by orlando** [comment]
@wioux Thanks for the getting back quickly and for the links, I'll see what we can come up with.

Cheers
